quick MD + DockFlow refactoring + ScoreFlow CLI
Implemented implicit solvent MD for ScoreFlow
Added a CLI for ScoreFlow
Refactored DockFlow
Updated exemple config files

diff --git a/DockFlow/DockFlow b/DockFlow/DockFlow
--- a/DockFlow/DockFlow
+++ b/DockFlow/DockFlow
@@ -1,9 +1,15 @@
 #!/bin/bash
 
+run_folder="$PWD"
+
+# Create a time stamp, in order to backup PLANTS output if it already exists
+datetime=$(date "+%Y%m%d%H%M%S")
+
 # Start up
 source $CHEMFLOW_HOME/DockFlow/DockFlow_interface.bash
 source $CHEMFLOW_HOME/DockFlow/DockFlow_functions.bash
 source $CHEMFLOW_HOME/common/check_mazinger_status.bash
+source $CHEMFLOW_HOME/common/ProgressBar.bash
 
 # Welcome user
 welcome
@@ -11,8 +17,12 @@ welcome
 # Source ChemFlow config file for paths
 source $CHEMFLOW_HOME/ChemFlow.config
 
-# Ask for user to configure or read from a .config file.
+# User interface
 DF_CLI "$@"
+
+# Write user parameters to a temporary file
+declare -p | awk '/declare --/ {print $3}' | awk 'f;/^_.*$/{f=1}' | grep -Fv -e "^_" -e "_list" > temp.config
+
 # if config file specified using the -f flag
 if [ ! -z "$CONFIG_FILE" ]; then
   echo "Reading configuration from $CONFIG_FILE"
@@ -20,37 +30,36 @@ if [ ! -z "$CONFIG_FILE" ]; then
 else
 # if a config file was not specified
   # if a config file exists in the current directory
-  if [ -f "${PWD}/DockFlow.config" ]; then
-    # ask the user
-    echo -n "Configuration file detected in the current directory ! Use it for DockFlow (y/n) : "
-    read answer
-    if [ "$answer" == "y" ]; then
-      source $PWD/DockFlow.config
-    elif [ "$answer" == "n" ]; then
-      write_DF_config
-    else
-      echo "Answer \"$answer\" not recognized ! Aborting..."
-      exit 1
-    fi
-  # else, read configuration from command line
+  if [ -f DockFlow.config ]; then
+    # Use this one instead
+    source DockFlow.config
+  # if no config file was specified and doesn't exist in the current directory
   else
-    write_DF_config
+    echo "${RED}FATAL ERROR${NC} : No configuration file found for DockFlow"
+    usage
+    exit 1
   fi
 fi
+# Overwrite parameters in config files with user parameters
+write_DF_config
 
 # Prepare folders and input file to run
-prepare_plants
+prepare_docking
 
 # Run plants with the options
 run_plants
 
-# Extract scores
-if [ ! "${run_mode}" = "mazinger" ]; then
-  echo -ne "Docking finished !"
-  plants_score_csv
-else
-  check_mazinger_status
-  plants_score_csv
+# copy config file to output folder
+cp ${run_folder}/DockFlow.config ${run_folder}/docking/
+
+# If running on mazinger, wait untill all jobs are finished
+if [ ${run_mode} = "mazinger" ]; then mazinger_progress_bar ${run_folder}/docking/jobs_list_${datetime}.mazinger; fi
+
+# If some results are missing, count how many and output it
+if [ -f docking/errors.csv ]; then
+  errorcount=$(cat docking/errors.csv | wc -l)
+  echo -e "${RED}ERRORS detected${NC} : ${errorcount}"
+  echo "See docking/errors.csv for more info"
 fi
 
 # exit
diff --git a/ScoreFlow/ScoreFlow b/ScoreFlow/ScoreFlow
--- a/ScoreFlow/ScoreFlow
+++ b/ScoreFlow/ScoreFlow
@@ -1,5 +1,8 @@
 #!/bin/bash
-run_folder=$PWD
+run_folder="$PWD"
+
+# Create a time stamp, in order to make backups
+datetime=$(date "+%Y%m%d%H%M%S")
 
 # Start up
 source $CHEMFLOW_HOME/ScoreFlow/ScoreFlow_interface.bash
@@ -13,8 +16,31 @@ welcome
 # Source ChemFlow config file for paths
 source $CHEMFLOW_HOME/ChemFlow.config
 
-# Ask for user to configure or read from a .config file.
-source ${PWD}/ScoreFlow.config
+# User interface
+SF_CLI "$@"
+
+# Write user parameters to a temporary file
+declare -p | awk '/declare --/ {print $3}' | awk 'f;/^_.*$/{f=1}' | grep -Fv -e "^_" -e "_list" > temp.config
+
+# if config file specified using the -f flag
+if [ ! -z "$CONFIG_FILE" ]; then
+  echo "Reading configuration from $CONFIG_FILE"
+  source "$CONFIG_FILE"
+else
+# if a config file was not specified
+  # if a config file exists in the current directory
+  if [ -f ScoreFlow.config ]; then
+    # Use this one instead
+    source ScoreFlow.config
+  # if no config file was specified and doesn't exist in the current directory
+  else
+    echo "${RED}FATAL ERROR${NC} : No configuration file found for ScoreFlow"
+    usage
+    exit 1
+  fi
+fi
+# Overwrite parameters in config files with user parameters
+write_SF_config
 
 # Check input file and make list of poses to rescore
 prepare_rescoring
@@ -32,21 +58,21 @@ elif $(list_include_item "PB3 GB5 GB8" "${scoring_function}"); then
 fi
 
 # copy config file to output folder
-cp ${run_folder}/ScoreFlow.config ${run_folder}/output/${scoring_function}_rescoring/
+cp ${run_folder}/ScoreFlow.config ${run_folder}/rescoring/${scoring_function}/
 
 # If running on mazinger, wait untill all jobs are finished
-if [ ${run_mode} = "mazinger" ]; then mazinger_progress_bar; fi
+if [ ${run_mode} = "mazinger" ]; then mazinger_progress_bar ${run_folder}/output/${scoring_function}_rescoring/jobs_list_${datetime}.mazinger; fi
 
 # Remove empty directories
-cd ${run_folder}/output/${scoring_function}_rescoring
+cd ${run_folder}/rescoring/${scoring_function}/
 rmdir --ignore-fail-on-non-empty * &> /dev/null
 cd ${run_folder}
 
 # If some results are missing, count how many and output it
-if [ -f output/${scoring_function}_rescoring/errors.csv ]; then
-  errorcount=$(cat output/${scoring_function}_rescoring/errors.csv | wc -l)
+if [ -f rescoring/${scoring_function}/errors.csv ]; then
+  errorcount=$(cat rescoring/${scoring_function}/errors.csv | wc -l)
   echo -e "${RED}ERRORS detected${NC} : ${errorcount}"
-  echo "See output/${scoring_function}_rescoring/errors.csv for more info"
+  echo "See rescoring/${scoring_function}/errors.csv for more info"
 fi
 
 # Exit
