Handling SMILES and SDF files with DockFlow
DockFlow now handles SDF and SMILES files (converts them to MOL2).
DockFlow automatically splits any file in 1 MOL2 file per ligand.
Small changes to SmilesTo3D.py to remove the progressbar
Fixed the install.sh script
Fixed DockFlow automatically reading DockFlow.config if no config file was specified in the command line (issue #25)

diff --git a/DockFlow/DockFlow b/DockFlow/DockFlow
--- a/DockFlow/DockFlow
+++ b/DockFlow/DockFlow
@@ -34,16 +34,9 @@ if [ ! -z "$CONFIG_FILE" ]; then
   source "$CONFIG_FILE"
 else
 # if a config file was not specified
-  # if a config file exists in the current directory
-  if [ -f DockFlow.config ]; then
-    # Use this one instead
-    source DockFlow.config
-  # if no config file was specified and doesn't exist in the current directory
-  else
-    echo -e "${RED}FATAL ERROR${NC} : No configuration file found for DockFlow"
-    usage
-    exit 1
-  fi
+  echo -e "${RED}FATAL ERROR${NC} : No configuration file found for DockFlow"
+  usage
+  exit 1
 fi
 
 # Overwrite parameters in config files with user parameters
diff --git a/Tools/splitmol b/Tools/splitmol
--- a/Tools/splitmol
+++ b/Tools/splitmol
@@ -74,23 +74,33 @@ error_count=0
 splitmol_CLI "$@"
 
 # Count # of molecules
-end=$(grep "TRIPOS>MOLECULE" ${input} |wc -l)
+filename=$(basename "${input}")
+extension="${filename##*.}"
+if [ "${extension}" = "mol2" ]; then
+  end=$(grep "TRIPOS>MOLECULE" ${input} |wc -l)
+elif  [ "${extension}" = "sdf" ]; then
+  end=$(grep "M  END" ${input} |wc -l)
+else
+  echo -e "${RED}ERROR${NC} : not a mol2 or sdf file"
+  exit 1
+fi
 
-# Split 
+# Split
 for ((i=1;i<=${end};i=$i+${maxmol}))
 do
   let finish=${i}+${maxmol}-1
-  if [ ${finish} -gt ${end} ] ; then finish=${end} ; fi 
+  if [ ${finish} -gt ${end} ] ; then finish=${end} ; fi
+  echo -ne "\rSplitting file ${i}/${end}         "
   babel ${input} ${output}_${i}_${finish}.${format_o} -f ${i} -l ${finish} >> babel.job 2>&1
 
   # check
-  if [ -f ${output}_${i}_${finish}.${format_o} ]; then 
-    rm -f babel.job
-  else
+  if [ ! -f ${output}_${i}_${finish}.${format_o} ]; then
     let error_count+=1
   fi
 done
-
-if [ $error_count -gt 0 ]; then
+# check for errors
+if [ "${error_count}" -eq 0 ]; then
+  rm -f babel.job
+else
   echo "$error_count error(s) detected. Check babel.job for more info"
 fi
